# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/dan/Desktop/electronics/vivado/06_demo_all.cache/wt [current_project]
set_property parent.project_path C:/Users/dan/Desktop/electronics/vivado/06_demo_all.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/dan/Desktop/electronics/vivado/06_demo_all.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/pmod_oled/charLib.coe
read_vhdl -library xil_defaultlib {
  {C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/New folder/CoeffHelpers.vhd}
  {C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/New folder/standard_additions_c.vhd}
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/pmod_oled/Delay.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/pmod_oled/OledInit.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/pmod_oled/OledUser.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/pmod_oled/PmodOLEDCtrl.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/pmod_oled/SpiCtrl.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/clk_prescaler.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/fifo_ram.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/data_processing_input.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/pipeline.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/my_FIR_filter.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/my_filter.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/data_processing.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/dbg_pwm_out.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/i2c/i2c_master.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/i2c/i2c_wrapper.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/spi/spi_master.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/spi/spi_wrapper_1x.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/spi/spi_controller.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/uart/uart_tx.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/uart/uart_rx.vhd
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/uart/uart.vhd
  {C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/New folder/types.vhd}
  C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/sources_1/imports/src/fpga_top.vhd
}
read_ip -quiet C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/mem_oled_char_lib/ip/mem_oled_char_lib/mem_oled_char_lib.xci
set_property used_in_implementation false [get_files -all c:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/mem_oled_char_lib/ip/mem_oled_char_lib/mem_oled_char_lib_ooc.xdc]

read_ip -quiet C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/xadc_wiz_0/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/xadc_wiz_0/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/xadc_wiz_0/ip/xadc_wiz_0/xadc_wiz_0.xdc]

read_ip -quiet C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/clk_wiz_0/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/clk_wiz_0/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/clk_wiz_0/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/clk_wiz_0/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/constrs_1/imports/src/fpga_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/dan/Desktop/electronics/vivado/06_demo_all.srcs/constrs_1/imports/src/fpga_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top fpga_top -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_top_utilization_synth.rpt -pb fpga_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
